Rename variable

diff --git a/rsyncbk b/rsyncbk
--- a/rsyncbk
+++ b/rsyncbk
@@ -66,7 +66,7 @@ _set_disk_confirmation() {
     echo 'You have selected:'
     echo "$(_bold 'src') - $(_bold "${gl_src_info}")"
     echo "$(_bold 'dst') - $(_bold "${gl_dst_info}")"
-    read -rp 'Confirm? [y/n] ' gl_disk_confirm
+    read -rp 'Confirm? [y/n] ' gl_yes_no
 }
 
 _print_missing_commands() {
@@ -101,7 +101,7 @@ _select_disks() {
         gl_dst_info="$(echo "${gl_disks}" | awk -v dst="${gl_dst}" '$1 == dst')"
         echo ""
         _set_disk_confirmation
-        case "${gl_disk_confirm}" in
+        case "${gl_yes_no}" in
         [yY][eE][sS] | [yY])
             break
             ;;
@@ -109,7 +109,7 @@ _select_disks() {
             _set_disk_selection
             ;;
         *)
-            echo "$(_yellow 'Invalid input:') ${gl_disk_confirm}" >&2
+            echo "$(_yellow 'Invalid input:') ${gl_yes_no}" >&2
             ;;
         esac
     done
